const WORDS = ['BRAVE', 'WORLD', 'DREAM', 'LIGHT', 'VOICE', 'HUMAN', 'IDEAL', 'TRUTH', 'PEACE', 'UNITY'];
const today = new Date();
const answer = WORDS[(Math.floor(Date.UTC(today.getFullYear(), today.getMonth(), today.getDate()) / 86400000)) % WORDS.length];
const grid = document.querySelector('#wordGrid');
const keyboard = document.querySelector('#keyboard');
let ccCode = '', row = 0, guess = '', complete = false, checking = false;
const keys = ['QWERTYUIOP', 'ASDFGHJKL', 'ZXCVBNM'];

for (let i = 0; i < 30; i++) { const tile = document.createElement('div'); tile.className = 'word-tile'; grid.append(tile); }
keys.forEach((line, index) => { const lineEl = document.createElement('div'); lineEl.className = 'key-line'; if (index === 2) lineEl.innerHTML = '<button data-key="ENTER" class="word-key wide">Enter</button>'; [...line].forEach(letter => lineEl.innerHTML += `<button data-key="${letter}" class="word-key">${letter}</button>`); if (index === 2) lineEl.innerHTML += '<button data-key="BACK" class="word-key wide">⌫</button>'; keyboard.append(lineEl); });

document.querySelector('#ccForm').addEventListener('submit', event => { event.preventDefault(); ccCode = document.querySelector('#ccCode').value.trim().toUpperCase(); document.querySelector('#ccDisplay').textContent = ccCode; document.querySelector('#wordleEntry').hidden = true; document.querySelector('#wordleGame').hidden = false; });
keyboard.addEventListener('click', event => { const key = event.target.dataset.key; if (key) handleKey(key); });
document.addEventListener('keydown', event => { if (!document.querySelector('#wordleGame').hidden) handleKey(event.key === 'Backspace' ? 'BACK' : event.key === 'Enter' ? 'ENTER' : event.key.toUpperCase()); });

function handleKey(key) { if (complete || checking) return; if (/^[A-Z]$/.test(key) && guess.length < 5) { guess += key; renderRow(); } else if (key === 'BACK') { guess = guess.slice(0, -1); renderRow(); } else if (key === 'ENTER') submitGuess(); }
function renderRow() { [...grid.children].slice(row * 5, row * 5 + 5).forEach((tile, index) => tile.textContent = guess[index] || ''); }
async function submitGuess() { if (guess.length !== 5 || checking) return status('Enter five letters.'); checking = true; status('Checking word…'); const valid = await isRealWord(guess); checking = false; if (!valid) return status('Use a real five-letter word.'); const letters = [...answer]; [...grid.children].slice(row * 5, row * 5 + 5).forEach((tile, index) => { const letter = guess[index]; tile.classList.add(letter === answer[index] ? 'exact' : letters.includes(letter) ? 'present' : 'absent'); const key = keyboard.querySelector(`[data-key="${letter}"]`); if (key && !key.classList.contains('exact')) key.className = `word-key ${letter === answer[index] ? 'exact' : letters.includes(letter) ? 'present' : 'absent'}`; }); if (guess === answer) return finish(row + 1); row++; guess = ''; document.querySelector('#attemptDisplay').textContent = `${row + 1} / 6`; if (row === 6) finish(6, true); else status('Keep going.'); }
async function isRealWord(word) { if (word === answer) return true; try { const response = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word.toLowerCase()}`); return response.ok; } catch { return false; } }
function status(text) { document.querySelector('#wordStatus').textContent = text; }
async function finish(attempts, missed = false) { complete = true; document.querySelector('#wordleGame').hidden = true; document.querySelector('#wordleResult').hidden = false; document.querySelector('#resultCode').textContent = ccCode; document.querySelector('#resultAttempts').textContent = missed ? 'Not solved' : `${attempts} / 6`; if (missed) { document.querySelector('#resultHeading').innerHTML = 'The word was<br /><em>' + answer + '.</em>'; document.querySelector('#resultNote').textContent = 'Thanks for playing.'; return; } try { const response = await fetch(`${SUPABASE_URL}/rest/v1/rpc/record_wordle_score`, { method: 'POST', headers: { 'Content-Type':'application/json', apikey:SUPABASE_PUBLISHABLE_KEY, Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}` }, body:JSON.stringify({ p_cc_code:ccCode, p_attempts:attempts }) }); if (!response.ok) throw new Error('Save failed'); const saved = await response.json(); document.querySelector('#resultHeading').innerHTML = saved ? 'First result<br /><em>recorded.</em>' : 'Thanks for<br /><em>playing again.</em>'; document.querySelector('#resultNote').textContent = saved ? 'Your first completed attempt has been permanently recorded.' : 'Your first completed result was already recorded and has not been changed.'; } catch { document.querySelector('#resultHeading').innerHTML = 'Result not<br /><em>saved.</em>'; document.querySelector('#resultNote').textContent = 'Please contact the event organiser.'; } }
